### ISSUE TITLE
Memory address check does not account for loop iterations

### ISSUE THREAD

**Issue by rgokulsm** [IBM/microprobe#10]
Hello @rbertran ,

There seems to be an issue with the memory addresses when the memory size exceeds the values reached within 1 iteration of the code loop.

This scenario has a small memory (uses  memory.GenericMemoryStreamsPass([[1, 1024, 1, 64, 1]])) works correctly and has the following memory access pattern:

```
 533500: system.cpu T0 : @rel_branch_3+4    : fsd ft1, 640(ra)           : FloatMemWrite :  D=0x0000000000000000 A=0x80003280
 533500: system.cpu T0 : @rel_branch_3+8    : sd t2, 704(ra)             : MemWrite :  D=0x0000000000000000 A=0x800032c0
 620500: system.cpu T0 : @rel_branch_3+12    : mul a0, s1, s0             : IntMult :  D=0x0000000000000000
 620500: system.cpu T0 : @rel_branch_3+16    : fld fa1, 768(ra)           : FloatMemRead :  D=0x0000000000000000 A=0x80003300
 620500: system.cpu T0 : @rel_branch_3+20    : lb a1, 832(ra)             : MemRead :  D=0x0000000000000000 A=0x80003340
 620500: system.cpu T0 : @rel_branch_3+24    : fld fa2, 896(ra)           : FloatMemRead :  D=0x0000000000000000 A=0x80003380
 620500: system.cpu T0 : @rel_branch_3+28    : mul a2, a5, a3             : IntMult :  D=0x0000000000000000
 620500: system.cpu T0 : @rel_branch_3+32    : beq a7, a6, 4              : IntAlu :
 620500: system.cpu T0 : @rel_branch_4    : sb a0, 960(ra)             : MemWrite :  D=0x0000000000000000 A=0x800033c0
 620500: system.cpu T0 : @rel_branch_4+4    : mul a4, s3, s2             : IntMult :  D=0x0000000000000000
 621000: system.cpu T0 : @rel_branch_4+8    : bne s4, a1, 4              : IntAlu :
 621000: system.cpu T0 : @rel_branch_5    : flw fa3, 0(ra)             : FloatMemRead :  D=0x0000000000000000 A=0x80003000

```

You will notice that the memory addresses loops back to 0x80003000 after 0x800033c0, since the size of the memory is 1024 bytes.

The next scenario errors outs with incorrect memory address. It uses the following: memory.GenericMemoryStreamsPass([[1, 1024*1024, 1, 64, 1]])

At the end of the first iteration of execution, the memory address limit is *not* reached which itself is fine. The last few addresses are shown below (note: the starting address was 80003000, so this has covered an address range of 4800, which is less than the total available) :

```
4747500: system.cpu T0 : @rel_branch_44+24    : sd s8, 1920(ra)            : MemWrite :  D=0x0000000000000000 A=0x80007780
4747500: system.cpu T0 : @rel_branch_44+28    : fadd_s fs8, fs4, fa0       : FloatAdd :  D=0x0000000000000000
4747500: system.cpu T0 : @rel_branch_44+32    : sb zero, 1984(ra)          : MemWrite :  D=0x0000000000000000 A=0x800077c0
4755500: system.cpu T0 : @rel_branch_44+36    : addi ra, ra, 2047          : IntAlu :  D=0x00000000800077ff
4755500: system.cpu T0 : @rel_branch_44+40    : c_addi ra, ra, 1           : IntAlu :  D=0x0000000080007800
4756000: system.cpu T0 : @rel_branch_44+42    : fmul_s fa7, fs0, fs10      : FloatMult :  D=0x0000000000000000
4833000: system.cpu T0 : @rel_branch_44+46    : sd t1, 0(ra)               : MemWrite :  D=0x0000000000000000 A=0x80007800

```

This is followed by:

```
4833500: system.cpu T0 : @rel_branch_44+56    : addi ra, ra, 2047          : IntAlu :  D=0x0000000080007fff
4833500: system.cpu T0 : @rel_branch_44+60    : addi ra, ra, 2047          : IntAlu :  D=0x00000000800087fe
4833500: system.cpu T0 : @rel_branch_44+64    : addi ra, ra, 2047          : IntAlu :  D=0x0000000080008ffd
4833500: system.cpu T0 : @rel_branch_44+68    : addi ra, ra, 2047          : IntAlu :  D=0x00000000800097fc
4833500: system.cpu T0 : @rel_branch_44+72    : addi ra, ra, 2047          : IntAlu :  D=0x0000000080009ffb
4833500: system.cpu T0 : @rel_branch_44+76    : addi ra, ra, 2047          : IntAlu :  D=0x000000008000a7fa
4833500: system.cpu T0 : @rel_branch_44+80    : addi ra, ra, 2047          : IntAlu :  D=0x000000008000aff9
4833500: system.cpu T0 : @rel_branch_44+84    : addi ra, ra, 2047          : IntAlu :  D=0x000000008000b7f8
4834000: system.cpu T0 : @rel_branch_44+88    : addi ra, ra, 2047          : IntAlu :  D=0x000000008000bff7
4834000: system.cpu T0 : @rel_branch_44+92    : c_addi ra, ra, 9           : IntAlu :  D=0x000000008000c000


```
 which is increasing the addresses by a huge chunk and thus wasting some space. Not sure if this is for alignment (to 4096 which is default).

After this in the next iteration we start from address 8000c000, which is okay. But now the check for address less than max size seems to go haywire. *This check does not seem to account for the loop iteration, so it always seems to be within the address range*.

This leads to a point (in some Nth iteration) when address hits the maximum and does not loop back:

```
163481500: system.cpu T0 : @rel_branch_39+12    : c_addi ra, ra, 1           : IntAlu :  D=0x0000000080103000

```

And this results in a fault.

Please let me know if i can provide more details - I'm not sure if my details convey the problem completely. In short I believe that the problem is that ***the memory address check, which should loop the memory address back to 0 when it crosses the max value, does not seem to take the iteration number multiplicative factor into account, thus it does not realize that the actual memory address has crossed the max bound***.

Thanks!

**Comment by rbertran** [comment]
After reproducing  the problem I found the issue: the updating of the base register was wrong, as you pointed out. We don't need to add such gap between iterations because the base register have been modified. This messed up the bound checking mechanism. I'll provide an update once CI checks finish later today.

**Comment by rbertran** [comment]
> This leads to a point (in some Nth iteration) when address hits the maximum and does not loop back

The stream pass assumes that you'll be continuously executing the loop. So, make sure that you generate an endless loop. To do so use the `endless=True` parameter during wrapper creation and
avoid resetting the state on each iteration  (`reset=False`), which is the default behavior.  E.g.:

```
cwrapper = get_wrapper('RiscvTestsP')
synth = Synthesizer(
    self.target,
    cwrapper(
        reset=False
        endless=True),
    value=0b01010101,
)
```

Loop will do not end, but you can control the execution externally.

**Comment by rgokulsm** [comment]
Thanks Ramon. Yes, I am running the endless loop and externally killing it gracefully after a few millions of instructions. I think the base register fix should solve "the failure in some ith iteration" which I described. I will confirm once your fix is available. Thanks again!!

**Comment by rbertran** [comment]
Repositories and packages updated! ;)

**Comment by rgokulsm** [comment]
Hi Ramon, it works perfectly now, thanks!! Closing this issue.

**Comment by rgokulsm** [comment]
Hi Ramon,

I am reopening this issue because there are still some scenarios where there seems to be some trouble.

I am able to run without errors for the following:

```
memory.GenericMemoryStreamsPass([[1, 32768, 1, 128, 1],[2, 32768, 2, 128, 2]]),
```

But I hit memory address related errors for:
```
memory.GenericMemoryStreamsPass([[1, 32768, 1, 128, 1],[2, 32768, 6, 128, 2]]),
```

The difference between the above 2 is the percentage of time the 2nd stream is executed is higher in the latter case.

**I am unsure if this is because of some ratio limitations, or are the base register checks you mentioned earlier getting messed up when there are multiple streams.**

Not sure if this helps, but this is how the bottom of the assembly (before the loop ends, looks):
```
ADDI x2, x0, 0x0
ADDI x7, x7, 0x1
ADDI x1, x1, 0x80
LUI x31, 0
ADDIW x31, x31, 0x3
BLT x7, x31, stream1guard
stream1_pcrel_3:AUIPC x1, %pcrel_hi(stream1)
ADDI x1, x1, %pcrel_lo(stream1_pcrel_3)
ADDI x7, x0, 0x0
stream2_pcrel_4:AUIPC x3, %pcrel_hi(stream2)
ADDI x3, x3, %pcrel_lo(stream2_pcrel_4)
ADDI x4, x0, 0x0
stream2_pcrel_5:AUIPC x5, %pcrel_hi(stream2)
ADDI x5, x5, %pcrel_lo(stream2_pcrel_5)
ADDI x6, x0, 0x0
stream1guard:ADDI x0, x0, 0x0

```

**Comment by rbertran** [comment]
I was unable to reproduce your error, but I detected something wrong when looking at the code generated (the one you pasted). The end of the bounds checking code of stream1 (`BLT x7, x31, stream1guard` ) was jumping all the bounds checking code of the other streams, and I think that in some scenarios that can lead to memory errors. The repos/packages will be updated in next minutes.

**Comment by rbertran** [comment]
repos updated. Let's see if that fixes the issues. If not, next time provide the set of passes with the actual inputs so that I can reproduce exactly your scenarios.

**Comment by rgokulsm** [comment]
Hey Ramon, It seems to be working fine after your fixes. Thanks, will close the issue.
