### ISSUE TITLE
Implementation of the "safe" binary decoding

### ISSUE THREAD

**Issue by ArnauBigas** [IBM/microprobe#28]
Hello,

I was wondering if the implementation of the "safe" binary decoding is complete or not, because I've had some problems with it. The implementation is mainly in `src/microprobe/utils/bin.py:139` and `src/microprobe/target/isa/instruction.py:150`. To begin with, the accesses to the instruction definition cache are not checked, and due to some reason (which I suspect is RiscV's variable length instructions or maybe the byte swapping due to endianess) it often crashes with the `MicroprobeDuplicatedValueError` exception.

If I disable the use of the cache, then the program fails later in the execution, during the codification stage. At that moment, it tries to apply some bit shifts to the operands, which seem to be hardcoded to strings and so generate python errors (can't bit shift a string). These strings appear to originate from the method in the `instruction.py` file mentioned earlier.

My current workaround is to simply not emit any new instructions when there is an error, but continue the decoding. But I understand this could possibly cause problems when reconstructing the instruction sequence, specially with relative jumps and such. I wonder if a better, and simpler, solution would be to just emit `NOP` instructions of the appropriate length?

Just in case, I am also providing an [mpt.tar.gz](https://github.com/IBM/microprobe/files/5837228/mpt.tar.gz) compressed archive containing an MPT with invalid (RiscV) instructions to test with.

**Comment by rbertran** [comment]
Fixed the issues:

- a) Byte switching is messing up the cache checking logic. 
- b) There was a bug forcing to use binary codification of an instruction with unresolved symbols (i.e. strings). 

Waiting for CI checks. 

Regarding a) , do you recall the reason to introduce the byte swap logic? I'm checking logs to understand... as it seems that is not needed when processing RISCV code.

**Comment by ArnauBigas** [comment]
I remember that there were some issues regarding the decoding of 2-byte instructions instead of the usual 4 bytes, where it was using the upper bits of the word instead of the lower bits (i.e. it was skipping 2 bytes). I will do some tests to see if the logic is really needed or if it was a mistake on my part by assuming the issue was the one I just described.

**Comment by rbertran** [comment]
ok. Current solution I have works for RISCV ... probably the requirement is coming from other back-ends that support both endian modes. Checking now.

**Comment by rbertran** [comment]
Latest test using the examples provided passed. I'm going to commit the code to the master branch and we can proceed with more extensive testing.

**Comment by rbertran** [comment]
Latest commit (01fa4dc4535c2f71099da7b7b1dc594f9907a55c)  should fix the issues.

**Comment by ArnauBigas** [comment]
Ok, so after some thought I have come to a few conclusions on why the current system isn't ideal and the steps we need to do to solve it.

The main issue is that, as far as I can tell, there isn't a clear contract on how the binary stream should be coded, or what are the expected parameters for the main binary decoding functions. In earlier approaches, we took into account the endianess of the architecture, but that is not enough because we also have to take into account the endianess of the input data and also the word size.

Take, for instance, the output generated by ChopStiX: a list of 4 byte words. These are concatenated and passed to the binary decodification system, creating essentially a big endian stream of binary data. Suppose next that we are using an ISA which uses 2 byte words for its instructions. Because the system is not aware of the input data properties, it currently decodes the first 2 bytes of the stream, and then successively decodes the ones after that. As you can imagine, by doing this MicroProbe will decode the higher bits of the original 4 byte word first, and then the lower bits.

In this example, if the ISA uses big endian encoding everything should be fine. However, if the ISA is little endian there are two possible outcomes: either the two bytes which form the word are swapped, resulting in a possibly invalid instruction, or two consecutive instructions are parsed in the wrong order.

As you can imagine, I used this example because it is what is happening currently with RiscV. However, I suspect the same issue is present if you use little endian input data with a big endian ISA.

I think the solution is to either document how the function expects the incoming data to be encoded, or to add additional parameters to the function signature to specify this kind of information. Then, the program should have the required information to do the necessary conversions and decode the right data with the right order. 

Once we come to an agreement, I could write the code and create a PR. I wouldn't mind. Or, if you prefer to write the code yourself, please go ahead.

**Comment by rbertran** [comment]
I assume that the current solution is working.  That said, I agree that the current solution (with undocumented assumptions for different targets) is far from ideal.  You are right, the endianess issue it is not only about the target endianess but also the input data endianness ...  

Given the two options, (a) documenting and assume a particular input stream endianness or (b) add a parameter about the input stream endianness, I'm more favorable to (b). It provides more flexibility to the API users and it is generic. Users just need to know the endianness of the provided stream (no need to re-codify the stream, which might be cumbersome on variable-length ISAs). At first sight, that will imply:

- replace the current `switch_endian` parameter, with a `input_stream_endianness`? optional parameter in `interpret_bin`. Default value should be target endianness.
- add the corresponding flag (e.g. `--raw-bin-endianness`?) to `mp_mpct2c` tool
- implement the necessary logic internally in `interpret_bin` (based on target endiannes and input stream endianness).

Do I miss something? If you agree, please go ahead, and feel free to post a PR when time permits.

Thanks!
