### ISSUE TITLE
[RISC-V] Failure to set register value when the upper 32 bits are all ones

### ISSUE THREAD

**Issue by ArnauBigas** [IBM/microprobe#34]
The RISC-V isa.py's `set_register` function fails to set the value 0xFFFFFFFF3C23D70A to a register. The critical code failing is:

```python
if value_high > 2047:
    value_highest = value_highest + 1
    value_high = value_high - (4096)

lui = self.new_instruction("LUI_V0")
lui.set_operands([value_highest, register])
instrs.append(lui)
```

In this code snippet, `value_highest = 0xFFFFF` and `value_high =  0xFFF`. This causes `value_highest` to become a value out of the 20-bit immediate range of the LUI instruction. I think the code should be revised in greater detail, as I remember encountering a similar problem in the past. This might be a regression caused by ce0ae0d73309d95756a312c34842db08c27fd8f5.

Find attached the [log.txt](https://github.com/IBM/microprobe/files/8068709/log.txt) and the [microbenchmark.zip](https://github.com/IBM/microprobe/files/8068715/microbenchmark.zip) to reproduce this issue.

Thanks.

**Comment by ArnauBigas** [comment]
I forgot to mention, the command I used to find this issue is `mp_mpt2test.py -T riscv_v22-riscv_generic-riscv64_linux_asmld --raw-bin --endless --wrap-function --reset-registers -O test.s -t test.mpt`. It was found using my branch (`mpt2test-memory-state-replication`), although the same code is on master so I assume it's not an issue on my branch.

**Comment by rbertran** [comment]
Latest commit 46d17a9744b943bb448fc5e2872f3521084d8bec fixes this issue. Closing it.
