### ISSUE TITLE
How to set up a model for a GenericMemoryStreamsPass?

### ISSUE THREAD

**Issue by rgokulsm** [IBM/microprobe#7]
This is an extension to question #6 .

Could you please provide details (or an example)  on how to setup a 'model' for a GenericMemoryStreamsPass (implemented at src/microprobe/passes/memory). My understanding from @rbertran's response in question #6  is that the model should be able to provide information on multiple memory streams. Thanks!

Thanks,
Gokul

**Comment by rbertran** [comment]
@rgokulsm 

The GenericMemoryStreamsPass accepts the following parameter:

- **model** : list of stream definitions, where each stream definition is a list with the following elements:
  - **stream id** : integer , id of the stream (it should be unique)
  - **size** :  size in bytes of the data that will be accessed by the stream. (An array variable will this size is going to be allocated in memory)
  - **ratio** : integer, weight of this stream (relative to other streams defined) . If this set to 1 and another stream is set to 2, the sequence of accesses will be 1,2,2,1,2,2,1,2,2 ...
  - **stride:** integer, distance between accesses of the stide in bytes (e.g. 64 bytes)
  - **streams** : integer, not used. Just use 0. 

And the following named parameters:

- **loadsonly**: bool , only modify load instructions
- **storesonly**: bool, only modify store instructions
- **switch_stores**: modify the stores so that in each loop  iterations the value to be stores changes from 0x555...555 to 0xAAA...AAA alternatively. This maximizes data switching pattern.
- **shift_streams**: integer, amount if shifting between streams. If this is zero all streams will be aligned, i.e. start from a zero displacement from the base address. 
- **warmstores**: bool, some architectures are store non-allocate policy of the first level of the cache and therefore if a value is not loaded first it will always miss on the L1 on stores. If this is set, all the store addresses are 'touched' by a lost before the loop starts. 

Examples:
- A single memory stream going through 4MB of memory in steps of 128 bytes using only load operations
    - `GenericMemoryStreamsPass([[0, 4 * 1024 * 1024, 1, 128, 0]], loadsonly=True)`
- Two memory stream going through 4MB and 256 bytes of memory in steps of 128, 64 bytes bytes respectively, where every 15 memory accesses 10 use stream 1 and 5 use stream 2:
    - `GenericMemoryStreamsPass([[0, 4 * 1024 * 1024, 10, 128, 0], [1, 256, 5, 64, 0]])`

**Comment by rgokulsm** [comment]
Hello Ramon,

Apologies for delayed response. I just tested out the above examples and I am running into some issues:

###### 1) I am trying the following:

``` python

passes = [

                    structure.SimpleBuildingBlockPass(self.args.loop_size),

                    initialization.InitializeRegistersPass(),

                    initialization.InitializeRegistersPass(v_value=(1.000000000000001, 64)),

                    instruction.SetInstructionTypeByProfilePass(thisdict),

                    address.UpdateInstructionAddressesPass(),

                    memory.GenericMemoryStreamsPass([[0, 4 * 1024 * 1024, 1, 128, 0]], loadsonly=True),

                    branch.BranchNextPass(),

                    register.DefaultRegisterAllocationPass(dd=1),

                    address.UpdateInstructionAddressesPass()

                   ]

```

###### 2) I get the following error:

``` 

\Traceback (most recent call last):

  File "riscv_flex.py", line 204, in <module>

    RiscvIpcTest().emit()

  File "riscv_flex.py", line 186, in emit

    bench = synth.synthesize()

  File "/research/sgokul/MicroProbe/microprobe/src/microprobe/code/__init__.py", line 400, in synthesize

    step(bench, self.target)

  File "/research/sgokul/MicroProbe/microprobe/src/microprobe/passes/memory/__init__.py", line 2037, in __call__

    reg_base = reg_basel[sind]

IndexError: list index out of range


```


###### 3) It seemed to me like the **streams** variable needed to be non-zero, so then I tried setting it to 1. When I tried that i got past the previous error but then hit the following:


```

Traceback (most recent call last):

  File "riscv_flex.py", line 204, in <module>

    RiscvIpcTest().emit()

  File "riscv_flex.py", line 186, in emit

    bench = synth.synthesize()

  File "/research/sgokul/MicroProbe/microprobe/src/microprobe/code/__init__.py", line 400, in synthesize

    step(bench, self.target)

  File "/research/sgokul/MicroProbe/microprobe/src/microprobe/passes/memory/__init__.py", line 2115, in __call__

    [reg_idx, reg_idx, diff])

  File "/research/sgokul/MicroProbe/microprobe/src/microprobe/code/ins.py", line 1817, in set_operands

    raise exc

microprobe.exceptions.MicroprobeValueError: Invalid operand value: '      X2 : General Purpose Register 2 (Type: ireg)'. Integer required and '<class 'researchsgokulMicroProbemicroprobetargetsriscvisariscvcommonregisterpyRISCVRegister.RISCVRegister'>' provided


```



###### 4) This error seems to be tied to the code:

``` python

                       if (len(calc_instrs) > 0 and diff <
                                32767 and diff > -32768):

                            calc_instr = calc_instrs[0]
                            calc_instr.set_operands(
                                [reg_idx, reg_idx, diff])

                            building_block.context.set_register_value(
                                reg_idx,
                                building_block.context.get_register_value(
                                    reg_idx) +
                                diff
                            )

                            memoperand.set_address(
                                address,
                                building_block.context)

                            tinstrs = [calc_instr]
                            new_instrs = []
                            reg_base_val_new = reg_base_val
                            reg_idx_val_new = reg_idx_val + diff

                            LOG.debug(
                                "Unable to generate the address. Fixing "
                                "Context to allow the generation"
                            )


```

I didn't want to go too deep down the incorrect path, so let me know what you think. Thanks!

**Comment by rbertran** [comment]
@rgokulsm 

My fault. I told you to use 0 on the last parameter, but it should be 1. So, the pass:
`memory.GenericMemoryStreamsPass([[0, 4 * 1024 * 1024, 1, 128, 0]], loadsonly=True),`
should be defined as:
`memory.GenericMemoryStreamsPass([[0, 4 * 1024 * 1024, 1, 128, 1]], loadsonly=True),`
The definition needs at least 1 stream. I've updated the previous comment accordingly. 

That said, after debugging that particular issue, I've also encountered some other limitations/bugs when generating addresses on the RISC-V port.  They have been fixed and in the following hours, once CI test suite is validated, the changes will be populated to the public github & PyPi repos.

**Comment by rgokulsm** [comment]
Awesome thanks. I will test and update, once it is  available

**Comment by rbertran** [comment]
Fixes (2cf9ec55159bb78fae33cfa6f1bdce752f63f3da) should be already in the latest github & PyPi repos.

**Comment by rgokulsm** [comment]
Hello Ramon, I tested it out now and I am running into some issue (albeit a different one).

My generation code is below:
```

 passes = [
                    structure.SimpleBuildingBlockPass(self.args.loop_size),
                    initialization.InitializeRegistersPass(),
                    initialization.InitializeRegistersPass(v_value=(1.000000000000001, 64)),
                    instruction.SetInstructionTypeByProfilePass(thisdict),
                    address.UpdateInstructionAddressesPass(),

                    memory.GenericMemoryStreamsPass([[1, 4 * 1024 * 1024, 1, 128, 1]], loadsonly=True),
                  
                    branch.BranchNextPass(),
                    register.DefaultRegisterAllocationPass(dd=9),
                    address.UpdateInstructionAddressesPass()

                ]

```

The error I hit is:

```
research/sgokul/MicroProbe/microprobe/targets/riscv/examples/build_flex/../riscv_flex/gokul_12345.S: Assembler messages:
/research/sgokul/MicroProbe/microprobe/targets/riscv/examples/build_flex/../riscv_flex/gokul_12345.S:584: Error: symbol `stream1_pcrel' is already defined
/research/sgokul/MicroProbe/microprobe/targets/riscv/examples/build_flex/../riscv_flex/Makefile:30: recipe for target 'riscv_new-p-gokul_12345' failed
make[1]: *** [riscv_new-p-gokul_12345] Error 1


```

The error in the is seemed to be related to **stream1_pcrel** which is "defined" twice in the in the generated .S file:
```
  7 .comm stream1, 4194304, 4096
  8 
  9 /* Start Main */
 10 RVTEST_RV64UF
 11 RVTEST_CODE_BEGIN
 12 
 13 reset:stream1_pcrel:AUIPC x1, %pcrel_hi(stream1)
 14 ADDI x1, x1, %pcrel_lo(stream1_pcrel)

```
and
```
583 BLT x15, x31, stream1guard
584 stream1_pcrel:AUIPC x1, %pcrel_hi(stream1)
585 ADDI x1, x1, %pcrel_lo(stream1_pcrel)
586 ADDI x0, x15, 0x0
587 stream1guard:ADDI x0, x0, 0x0
588 /* Loop End */
589 j first
590 /* End Main */

```

Please let me know what you think, thanks!

**Comment by rbertran** [comment]
@rgokulsm I found the issue and I fixed it. Once the CI testing finishes in the following ours, the repository/packages will be updated.

**Comment by rbertran** [comment]
Repository and pip packages updated.  I was unable to test the functionality of the generated codes, but I was able to compile the code, and the assembly listing looks fine.

**Comment by rgokulsm** [comment]
Hello @rbertran ,

Thanks for the update. I am able to compile it but I am hitting some different errors while running it..

Here is a snippet of the erroring code generated using the generic memory stream pass (memory.GenericMemoryStreamsPass([[1, 1024, 1, 4, 1]])):

```
  6 .comm riscv_v22_scratch_var, 256
  7 .comm stream1, 1024, 4096
  8 
  9 /* Start Main */
 10 RVTEST_RV64UF
 11 RVTEST_CODE_BEGIN
 12 
 13 reset:stream1_pcrel_1:AUIPC x1, %pcrel_hi(stream1)
 14 ADDI x1, x1, %pcrel_lo(stream1_pcrel_1)
 15 ADDI x0, x2, 0x0
 16 /* Building block start */
 17 first:FLD f0, 0x0(x1) /* Address: Address((char) stream1[1024]+0x0000000000000000) */
 18                       /* Loop start */
 19 FADD.S f3, f2, f1
 20 FLD f4, 0x4(x1) /* Address: Address((char) stream1[1024]+0x0000000000000004) */
 21 LW x0, 0x8(x1) /* Address: Address((char) stream1[1024]+0x0000000000000008) */
 22 BNE x4, x3, stream1+0xc /* Address: Address((char) stream1[1024]+0x000000000000000c) */
 23 BNE x6, x5, stream1+0x10 /* Address: Address((char) stream1[1024]+0x0000000000000010) */
 24 SW x7, 0x14(x1) /* Address: Address((char) stream1[1024]+0x0000000000000014) */

```

Here is a snippet of the working code generated with the single memory stream pass ( memory.SingleMemoryStreamPass(1024, 4))

```
  6 .comm ST_1024_4_0, 4100
  7 .comm riscv_v22_scratch_var, 256
  8 
  9 /* Start Main */
 10 RVTEST_RV64UF
 11 RVTEST_CODE_BEGIN
 12 
 13 reset:ADDI x0, x1, 0x0
 14 ST_1024_4_0_pcrel_1:AUIPC x2, %pcrel_hi(ST_1024_4_0)
 15 ADDI x2, x2, %pcrel_lo(ST_1024_4_0_pcrel_1)
 16 /* Building block start */
 17 first:FLD f0, 0x0(x2) /* Address: Address((char) ST_1024_4_0[4100]+0x0000000000000000) */
 18                       /* Loop start */
 19 FADD.S f3, f2, f1
 20 FLD f4, 0x4(x2) /* Address: Address((char) ST_1024_4_0[4100]+0x0000000000000004) */
 21 LW x0, 0x8(x2) /* Address: Address((char) ST_1024_4_0[4100]+0x0000000000000008) */
 22 BNE x4, x3, rel_branch_0 /* Branch fixed to: InstructionAddress(rel_branch_0+0x0000000000000000) */
 23 rel_branch_0:BNE x6, x5, rel_branch_1 /* Branch fixed to: InstructionAddress(rel_branch_1+0x0000000000000000) */
 24 rel_branch_1:SW x7, 0xc(x2) /* Address: Address((char) ST_1024_4_0[4100]+0x000000000000000c) */

```

There are a couple of significant differences (not sure if they are related to the error though): a) The memory/stream location in the 2 cases (line #6/7) are different and b) I notice that the branch address for the branches in the 2 codes (line #22/23) are defined differently. Is the branch address correct in the generic memory stream case?

When I run the erroring simulation (i.e. the generic memory stream case) and try to trace it, I seem to execute until just before the branch instructions in line #22/23. I am still verifying this - so not a 100% sure that this is the case. The error is the following:

```
panic: Illegal instruction 0x00000000 at pc 0x0000000080003010
```

Let me know if I can provide more details, thanks!

**Comment by rbertran** [comment]
Problems solved and CI checking. There were issues here and there due to not doing a functional validation of the code. Now, I use spike to validate that the code generate runs. I'll be updating the repos in the following hours once all checks pass.

**Comment by rbertran** [comment]
Repos updated. Let me know if you find any other issue. If that's the case, please sent to me your benchmark generation policy and I'll make sure that code generated using the different parameters you are exploring is valid.

Thanks for the patience in going through the process of validating the extended features of the RISCV port which were never _fully_ tested properly :(

**Comment by rgokulsm** [comment]
Thank you for the immediate updates Ramon. I will try this out asap and let you know.
I'm happy to validate and test! ;)

**Comment by rgokulsm** [comment]
Hello Ramon,

I confirm that I am able to run with the generic memory stream pass - I tried with different memory streams as well as a combination of two streams - and they all seem to work okay. I will close this issue. I still have a problem simulating with large memory footprints (when the relative address cross 0x7ff) - which I had brought up earlier in issue #9 . I will continue that discussion there. 

Thank you for your support and immediate updates!!
